name: Build and Preview
on:
  push:
    branches: ["main"]

jobs:
  build_ios:
    name: iOS Development Build
    runs_on: linux-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build iOS
        uses: expo/eas-build-action@v1
        with:
          platform: ios
          profile: development
