name: Build and Preview
on:
  push:
    branches: ["main"]

jobs:
  ios_build_job:
    name: iOS Development Build
    type: build
    params:
      platform: ios
      profile: development

  android_build_job:
    name: Android Development Build
    needs: [ios_build_job]
    type: build
    params:
      platform: android
      profile: development
